version: '3.8'
services:
  file_space:
    container_name: file_space
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "8080:8080"
    links:
      - db_postgres
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    links:
      - file_space
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8085:8085"
  db_postgres:
    container_name: db_postgres
    image: postgres:11-alpine
    restart: always
    volumes:
    -  ../postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: file_space