version: '3.8'
services:
  file_space:
    container_name: file_space
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "8080:8080"
    links:
      - postgres
      - neo4j
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    links:
      - file_space
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8085:8085"
  postgres:
    image: postgres:11-alpine
    container_name: db_postgres
    restart: always
    volumes:
    -  ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: file_space
  neo4j:
    container_name: db_neo4j
    image: neo4j:4.2.0
    restart: always
    ports:
      - "7687:7687"
      - "7474:7474"